# Use the official Debian base image
FROM debian:latest

# Install Nginx and OpenSSL
RUN apt-get update && apt-get install -y nginx openssl

# Remove the default Nginx configuration
RUN rm -v /etc/nginx/nginx.conf

# Copy custom configuration file from the host into the container
COPY nginx.conf /etc/nginx/nginx.conf

# Generate self-signed SSL certificate and key
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/ssl/private/server.key \
    -out /etc/ssl/certs/server.crt \
    -subj "/C=IT/ST=Lazio/L=Rome/O=Zong/CN=Zong.com"

# Expose the ports specified by the environment variable
EXPOSE 443

# Command to start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]